#!/bin/bash
# Generated by add-device.sh
SERIAL="100.68.167.90:5555"

# Silent Connect
adb connect $SERIAL > /dev/null 2>&1

# Launch Logic (High-Res Tablet Optimized)
# Max height 1080p to save bandwidth, 60fps for smoothness
exec scrcpy -s $SERIAL \
       --window-title "Galaxy Tab 6" \
       --max-size 1080 --max-fps 60 --video-bit-rate 10M \
       --always-on-top --turn-screen-off --stay-awake > /dev/null 2>&1
