#!/bin/bash

# Colors for pretty output
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${CYAN}=== Omarchy Android Device Wizard ===${NC}"

# 1. Gather Information
read -p "Enter Device Friendly Name (e.g., 'Galaxy Tab S9'): " DEVICE_NAME
read -p "Enter Short ID (no spaces, e.g., 'tablet'): " DEVICE_ID
read -p "Enter Tailscale IP (e.g., 100.x.y.z): " DEVICE_IP

# 2. The Physical Connection (The "Lock")
echo -e "\n${CYAN}--- Step 2: ADB Port Lock ---${NC}"
echo "Please connect the $DEVICE_NAME via USB cable now."
read -p "Press [Enter] when connected..."

# Force TCP mode on the USB device
echo "Setting TCP/IP to 5555..."
adb -d tcpip 5555

echo -e "${GREEN}Success! You may unplug the USB cable now.${NC}"
read -p "Press [Enter] to continue..."

# 3. Generate the Controller Script
SCRIPT_DIR="$HOME/Work/adb/$DEVICE_ID"
SCRIPT_PATH="$SCRIPT_DIR/${DEVICE_ID}-ctl.sh"

mkdir -p "$SCRIPT_DIR"

echo "Generating script at $SCRIPT_PATH..."

# Write the file template
cat <<EOF > "$SCRIPT_PATH"
#!/bin/bash
# Generated by add-device.sh
SERIAL="${DEVICE_IP}:5555"

# Silent Connect
adb connect \$SERIAL > /dev/null 2>&1

# Launch Logic (High-Res Tablet Optimized)
# Max height 1080p to save bandwidth, 60fps for smoothness
exec scrcpy -s \$SERIAL \\
       --window-title "$DEVICE_NAME" \\
       --max-size 1080 --max-fps 60 --video-bit-rate 10M \\
       --always-on-top --turn-screen-off --stay-awake > /dev/null 2>&1
EOF

# Make executable
chmod +x "$SCRIPT_PATH"

# 4. Symlink to System Path
echo "Symlinking to ~/.local/bin..."
ln -sf "$SCRIPT_PATH" "$HOME/.local/bin/${DEVICE_ID}-ctl"

# 5. Register in Device List
LIST_FILE="$HOME/Work/adb/devices.list"
# Append entry: "Icon Name|command"
# We add a default tablet icon , you can edit later
echo "  $DEVICE_NAME|${DEVICE_ID}-ctl" >> "$LIST_FILE"

echo -e "\n${GREEN}=== Setup Complete! ===${NC}"
echo "Try pressing Super + Shift + I to see your new device!"
